---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb
spec:
  selector:
    app: dynamodb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: retask
spec:
  selector:
    app: retask
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
      name: p3
    - protocol: TCP
      port: 3332
      targetPort: 3332
      name: p2
    - protocol: TCP
      port: 3331
      targetPort: 3331
      name: p1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: retask
  name: retask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retask
  template:
    metadata:
      labels:
        app: retask
    spec:
      containers:
      - image: node:14
        name: retask
        workingDir: /usr/src/app
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dynamodb
  name: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
      - image: amazon/dynamodb-local:latest
        name: dynamodb-local
        workingDir: /home/dynamodblocal
        command:
          - "java"
          - "-Djava.library.path=./DynamoDBLocal_lib"
          - "-jar"
          - "DynamoDBLocal.jar"
          - "-sharedDb"
          - "-optimizeDbBeforeStartup"
          - "-dbPath"
          - "/home/dynamodblocal"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"

